server:
  port: 25567
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pillowdrive
    username: hyxpillow
    password: "0540"
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  mail:
    host: smtp.qq.com
    username: 401887202@qq.com
    password: "ikjfdovgujpgbjaf"
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#mybatis:
#  mapper-locations: classpath:mapper/*.xml